eva_snp:
  adapter:
    module: biocypher_metta.adapters.eva_adapter
    cls: EVAAdapter
    args:
      filepath: ./samples/cel/eva/6239_GCA_000002985.3_current_ids.vcf.gz
      taxon_id: 6239
      label: snp
  outdir: cel/eva
  nodes: True
  edges: False

eva_snp_in_gene:
  adapter:
    module: biocypher_metta.adapters.eva_adapter
    cls: EVAAdapter
    args:
      filepath: ./samples/cel/eva/6239_GCA_000002985.3_current_ids.vcf.gz
      gene_filepath: ./samples/cel/ensembl/Caenorhabditis_elegans.WBcel235.115.gtf.gz
      taxon_id: 6239
      label: snp_in_gene
  outdir: cel/eva
  nodes: False
  edges: True

wbbt:
  adapter:
    module: biocypher_metta.adapters.cel.wbbt_adapter
    cls: WbbtAdapter
    args:
      ontology: "wbbt"
      type: node
      label: anatomy
      dry_run: True
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: wbbt
  nodes: True
  edges: False

wbbt_subclass_of:
  adapter:
    module: biocypher_metta.adapters.cel.wbbt_adapter
    cls: WbbtAdapter
    args:
      ontology: "wbbt"
      type: edge
      label: anatomy_subclass_of
      dry_run: True
      cache_dir: ./ontology_dataset_cache
  outdir: wbbt
  nodes: False
  edges: True
