Title: BioCypher graph schema configuration file



##################             NODES   SECTION             ####################

chromosome:
  represented_as: node
  is_a: position entity
  mixins:
  - biolink:GenomicEntity
  biolink_category: biolink:GenomicEntity
  inherit_properties: true
  input_label: chromosome
  properties:
    chromosome_id:
      type: str

enhancer:
  represented_as: node
  input_label: enhancer
  is_a: non coding element
  mixins:
  - biolink:RegulatoryRegion
  biolink_category: biolink:RegulatoryRegion
  inherit_properties: true
  properties:
    data_source:
      type: str
      biolink: source_web_page
    enhancer_id:
      type: str
      biolink: id
    taxon_id:
      description: Taxon ID for the organism (e.g., 7227 for fruit fly, 9606 for human)
      type: int
      biolink: taxon
      range: biolink:OrganismTaxon
  kgx_properties:
    category: biolink:RegulatoryRegion

polyphen2 variant:
  represented_as: node
  is_a: genomic variant
  mixins:
  - biolink:SequenceVariant
  biolink_category: biolink:SequenceVariant
  inherit_properties: true
  input_label: polyphen2_variant
  description: A variant with PolyPhen-2 predictions for the impact of amino acid
    substitutions on protein structure and function
  kgx_properties:
    category: biolink:SequenceVariant
  properties:
    ref:
      type: str
    alt:
      type: str
    polyphen2_humdiv_score:
      type: float
      biolink: has_quantitative_value
    polyphen2_humdiv_prediction:
      type: str
    polyphen2_humvar_score:
      type: float
      biolink: has_quantitative_value
    polyphen2_humvar_prediction:
      type: str

snp:
  represented_as: node
  input_label: snp
  is_a: genomic variant
  mixins:
  - biolink:Snv
  biolink_category: biolink:Snv
  inherit_properties: true
  kgx_properties:
    category: biolink:Snv
  properties:
    ref:
      type: str
    alt:
      type: str
    caf_ref:
      type: str
    caf_alt:
      type: str
  description: A single nucleotide polymorphism (SNP) is a variation in a single nucleotide
    that occurs at a specific position in the genome

super enhancer:
  represented_as: node
  input_label: super_enhancer
  is_a: non coding element
  mixins:
  - biolink:RegulatoryRegion
  biolink_category: biolink:RegulatoryRegion
  inherit_properties: true
  properties:
    se_id:
      type: str
      biolink: id
    taxon_id:
      description: Taxon ID for the organism (e.g., 7227 for fruit fly, 9606 for human)
      type: int
      biolink: taxon
      range: biolink:OrganismTaxon
  kgx_properties:
    category: biolink:RegulatoryRegion



##################             EDGES   SECTION             ####################

activity by contact:
  description: An association between a variant in a regulatory region and a gene
    it predicted by the ABC model (Fulco et.al 2019)
  is_a: regulatory association
  mixins:
  - biolink:VariantToGeneAssociation
  biolink_predicate: biolink:affects
  inherit_properties: true
  represented_as: edge
  input_label: activity_by_contact
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    score:
      type: float
      biolink: has_quantitative_value
    biological_context:
      type: str
      biolink: has_biological_sequence

chromatin state:
  is_a: association
  mixins:
  - biolink:GenotypeToPhenotypicFeatureAssociation
  biolink_predicate: biolink:has_phenotype
  represented_as: edge
  input_label: chromatin_state
  source: snp
  target: anatomy
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Cell
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    state:
      type: str
      biolink: phenotypic_state

closest gene to variant association:
  is_a: association
  mixins:
  - biolink:VariantToGeneAssociation
  biolink_predicate: biolink:associated_with
  description: holds between a sequence variant and a gene that is closest to the
    variant
  represented_as: edge
  input_label: closest_gene
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    chr:
      type: str
    pos:
      type: int
      biolink: start_interbase_coordinate
    distance:
      type: int
    source:
      type: str
      biolink: provided_by
    source_url:
      type: str
      biolink: source_web_page

dnase I hotspot:
  is_a: association
  mixins:
  - biolink:GenotypeToPhenotypicFeatureAssociation
  biolink_predicate: biolink:has_phenotype
  description: A region of chromatin that is sensitive to cleavage by the enzyme DNase
    I
  represented_as: edge
  input_label: in_dnase_I_hotspot
  source: snp
  target: anatomy
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Cell
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

downstream gene to variant association:
  is_a: closest gene to variant association
  mixins:
  - biolink:VariantToGeneAssociation
  biolink_predicate: biolink:associated_with
  inherit_properties: true
  description: holds between a sequence variant and a gene that is downstream to the
    variant
  represented_as: edge
  input_label: snp_downstream_gene
  output_label: downstream_of
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    distance:
      type: int
    p_value:
      type: float
      biolink: has_quantitative_value

gtex variant to gene expression association:
  aliases:
  - eQTL
  - e-QTL
  description: An association between a variant and expression of a gene (i.e. e-QTL)
  is_a: association
  mixins:
  - biolink:VariantToGeneExpressionAssociation
  biolink_predicate: biolink:correlated_with
  represented_as: edge
  input_label: gtex_variant_gene
  output_label: eqtl_association
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    slope: float
    maf: float
    p_value: float
    q_value: float
    biological_context: str
    source: str
    source_url: str

histone modification:
  is_a: association
  mixins:
  - biolink:GenotypeToPhenotypicFeatureAssociation
  biolink_predicate: biolink:has_phenotype
  description: A post-translational modification of histone proteins e.g methylation,
    acetylation, phosphorylation
  represented_as: edge
  input_label: histone_modification
  source: snp
  target: anatomy
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Cell
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    modification:
      type: str
      biolink: phenotypic_state

hpo subclass of:
  is_a: subclass of
  mixins:
  - biolink:PhenotypicFeatureToPhenotypicFeatureAssociation
  biolink_predicate: biolink:subclass_of
  inherit_properties: true
  represented_as: edge
  input_label: hpo_subclass_of
  output_label: is_a
  source: phenotype
  target: phenotype
  kgx_properties:
    subject_category: biolink:PhenotypicFeature
    object_category: biolink:PhenotypicFeature
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

in gene to variant association:
  is_a: closest gene to variant association
  mixins:
  - biolink:VariantToGeneAssociation
  biolink_predicate: biolink:located_in
  inherit_properties: true
  description: holds between a sequence variant and a gene that is within the gene
    body
  represented_as: edge
  input_label: snp_in_gene
  output_label: located_in
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    p_value:
      type: float
      biolink: has_quantitative_value

located on chain:
  is_a: association
  mixins:
  - biolink:GenomicSequenceLocalization
  biolink_predicate: biolink:part_of
  description: holds between a position entity and a chromosome chain
  represented_as: edge
  input_label: located_on_chain
  source: position_entity
  target: chromosome_chain
  kgx_properties:
    subject_category: biolink:GenomicEntity
    object_category: biolink:GenomicEntity
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

lower resolution structure:
  is_a: association
  mixins:
  - biolink:GenomicSequenceLocalization
  biolink_predicate: biolink:has_part
  description: holds between two chromosome chains where one is a lower resolution
    version of the other
  represented_as: edge
  input_label: lower_resolution
  source: chromosome_chain
  target: chromosome_chain
  kgx_properties:
    subject_category: biolink:GenomicEntity
    object_category: biolink:GenomicEntity
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

pathway_to_biological_process:
  is_a: association
  biolink_predicate: biolink:participates_in
  source: pathway
  target: biological process
  represented_as: edge
  input_label: pathway_to_biological_process
  output_label: equivalent_to
  description: An association between a pathway and a biological process, indicating
    that the pathway is involved in the process.
  properties:
    pathway_name: str
    go_term_id: str
    go_term_type:
      type: str
      const: biological process
    source:
      type: str
      biolink: knowledge_source
    source_url:
      type: str
      biolink: source_web_page
  kgx_properties:
    subject_category: biolink:Pathway
    object_category: biolink:BiologicalProcess
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

pathway_to_cellular_component:
  is_a: association
  source: pathway
  target: cellular component
  biolink_predicate: biolink:related_to
  represented_as: edge
  input_label: pathway_to_cellular_component
  description: An association between a pathway and a cellular component, indicating
    that the pathway is associated with the component.
  properties:
    pathway_name: str
    go_term_id: str
    go_term_type:
      type: str
      const: cellular component
  kgx_properties:
    subject_category: biolink:Pathway
    object_category: biolink:CellularComponent
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

pathway_to_molecular_function:
  is_a: association
  source: pathway
  target: molecular function
  biolink_predicate: biolink:related_to
  represented_as: edge
  input_label: pathway_to_molecular_function
  description: An association between a pathway and a molecular function, indicating
    that the pathway is involved in the function.
  properties:
    pathway_name: str
    go_term_id: str
    go_term_type:
      type: str
      const: molecular function
  kgx_properties:
    subject_category: biolink:Pathway
    object_category: biolink:MolecularActivity
    knowledge_level: knowledge_assertion
    agent_type: manual_agent

topld in linkage disequilibrium with:
  is_a: association
  biolink_predicate: biolink:in_linkage_disequilibrium_with
  description: holds between two sequence variants, the presence of which are correlated
    in a population
  represented_as: edge
  input_label: in_linkage_disequilibrium_with
  source: snp
  target: snp
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Snv
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    ancestry:
      type: str
    r2:
      type: float
      biolink: has_quantitative_value
    d_prime:
      type: float
      biolink: has_quantitative_value
    source:
      type: str
      biolink: provided_by
    source_url:
      type: str
      biolink: source_web_page

# transcribed from:
#   is_a: expression
#   mixins:
#   - biolink:TranscriptToGeneRelationship
#   biolink_predicate: biolink:transcribed_from
#   inherit_properties: true
#   represented_as: edge
#   input_label: transcribed_from
#   source: transcript
#   target: gene
#   kgx_properties:
#     subject_category: biolink:Transcript
#     object_category: biolink:Gene
#     knowledge_level: knowledge_assertion
#     agent_type: manual_agent
#   description: x is transcribed from y if and only if x is synthesized from template
#     y
#   exact_mappings:
#   - RO:0002510
#   - SIO:010081

transcription factor to snp association:
  is_a: association
  biolink_predicate: biolink:affects
  description: holds between a transcription factor and a snp if the snp occurs in
    a transcription factor binding site (tfbs)
  represented_as: edge
  input_label: tf_snp
  source: gene
  target: snp
  kgx_properties:
    subject_category: biolink:Gene
    object_category: biolink:Snv
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    effect:
      type: str
    score:
      type: float
      biolink: has_quantitative_value
    source:
      type: str
      biolink: primary_knowledge_source
    source_url:
      type: str
      biolink: source_web_page

upstream gene to variant association:
  is_a: closest gene to variant association
  mixins:
  - biolink:VariantToGeneAssociation
  biolink_predicate: biolink:associated_with
  inherit_properties: true
  description: holds between a sequence variant and a gene that is upstream to the
    variant
  represented_as: edge
  input_label: snp_upstream_gene
  output_label: upstream_of
  source: snp
  target: gene
  kgx_properties:
    subject_category: biolink:Snv
    object_category: biolink:Gene
    knowledge_level: knowledge_assertion
    agent_type: manual_agent
  properties:
    distance:
      type: int
    p_value:
      type: float
      biolink: has_quantitative_value
