pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathways.txt
      pubmed_map_path: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactionPMIDS.txt
      taxon_id: 7227
  outdir: reactome
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: genes_pathways
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: parent_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathways.txt
      pubmed_map_path: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactionPMIDS.txt
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: genes_pathways
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: parent_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True

tflink_:     
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/tflink/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          entrez_to_ensemble_map: ./aux_files/dmel/dmel_entrez_to_ensembl.pkl
          taxon_id: 7227
    outdir: tflink
    nodes: False
    edges: True

tflink:
  adapter:
    module: biocypher_metta.adapters.tflink_adapter
    cls: TFLinkAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/tflink/tflink_homo_sapiens_interactions.tsv.gz
      entrez_to_ensemble_map: ./aux_files/entrez_to_ensembl.pkl
      taxon_id: 9606
  outdir: tflink
  nodes: False
  edges: True
