pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathways.txt
      pubmed_map_path: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactionPMIDS.txt
      taxon_id: 7227
  outdir: reactome
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: genes_pathways
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: parent_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathways.txt
      pubmed_map_path: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactionPMIDS.txt
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/hsa/string_ensembl_uniprot_map.pkl
      label: genes_pathways
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/hsa/string_ensembl_uniprot_map.pkl
      label: parent_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/hsa/string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True


tflink_:    
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          filepath: ./samples/dmel/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          entrez_to_ensemble_map: ./aux_files/dmel/dmel_entrez_to_ensembl.pkl
          taxon_id: 7227          
    outdir: tflink_dmel
    nodes: False
    edges: True

tflink:
    adapter:
      module: biocypher_metta.adapters.tflink_adapter
      cls: TFLinkAdapter
      args:
        filepath: ./samples/hsa/tflink_homo_sapiens_interactions.tsv.gz
        entrez_to_ensemble_map: ./aux_files/hsa/entrez_to_ensembl.pkl
        taxon_id: 9606
    outdir: tflink
    nodes: False
    edges: True


gaf_biological_process_gene_product_:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/dmel/flybase/gene_association.fb.gz
      label: biological_process_gene_product
      gaf_type: 'flybase'
      gaf_source: 'flybase'
      taxon_id: 7227      
  outdir: gaf_dmel
  nodes: False
  edges: True

gaf_molecular_function_gene_product_:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/dmel/flybase/gene_association.fb.gz
      label: molecular_function_gene_product
      gaf_type: 'flybase'
      gaf_source: 'flybase'      
      taxon_id: 7227
  outdir: gaf_dmel
  nodes: False
  edges: True

gaf_cellular_component_gene_product_part_of_:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/dmel/flybase/gene_association.fb.gz
      label: cellular_component_gene_product_part_of
      gaf_type: 'flybase'
      gaf_source: 'flybase'      
      taxon_id: 7227
  outdir: gaf_dmel
  nodes: False
  edges: True

gaf_cellular_component_gene_product_located_in_:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/dmel/flybase/gene_association.fb.gz
      label: cellular_component_gene_product_located_in
      gaf_type: 'flybase'
      gaf_source: 'flybase'      
      taxon_id: 7227
  outdir: gaf_dmel
  nodes: False
  edges: True

gaf_biological_process_gene_product:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/hsa/goa_human_sample.gaf.gz
      label: biological_process_gene_product
      gaf_type: 'human'
      gaf_source: 'human'      
      taxon_id: 9606      
  outdir: gaf
  nodes: False
  edges: True

gaf_molecular_function_gene_product:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/hsa/goa_human_sample.gaf.gz
      label: molecular_function_gene_product
      gaf_type: 'human'
      gaf_source: 'human'        
      taxon_id: 9606
  outdir: gaf
  nodes: False
  edges: True

gaf_cellular_component_gene_product_part_of:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/hsa/goa_human_sample.gaf.gz
      label: cellular_component_gene_product_part_of
      gaf_type: 'human'
      gaf_source: 'human'      
      taxon_id: 9606
  outdir: gaf
  nodes: False
  edges: True

gaf_cellular_component_gene_product_located_in:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/hsa/goa_human_sample.gaf.gz
      label: cellular_component_gene_product_located_in
      gaf_type: 'human'
      gaf_source: 'human'      
      hgnc_to_ensembl_map: ./aux_files/hsa/hgnc_to_ensembl.pkl
      taxon_id: 9606
  outdir: gaf
  nodes: False
  edges: True

gaf_cellular_component_gene_product_located_in__:
  adapter:
    module: biocypher_metta.adapters.gaf_adapter
    cls: GAFAdapter
    args:
      filepath: ./samples/hsa/goa_human_sample.gaf.gz
      label: cellular_component_gene_product_located_in
      gaf_type: 'rna'
      gaf_source: 'rna'      
      taxon_id: 9606
  outdir: gaf
  nodes: False
  edges: True

# bgee_gene_expressed_in_anatomical_entity_dmel:
#   adapter:
#     module: biocypher_metta.adapters.bgee_adapter
#     cls: BgeeAdapter
#     args:
#       filepath: ./samples/dmel/bgee/Drosophila_melanogaster_expr_simple_all_conditions.tsv.gz
#       label: expressed_in
#       taxon_id: 7227
#   outdir: bgee_dmel
#   nodes: False
#   edges: True


# bgee_gene_expressed_in_anatomical_entity:
#   adapter:
#     module: biocypher_metta.adapters.bgee_adapter
#     cls: BgeeAdapter
#     args:
#       filepath: ./samples/hsa/Homo_sapiens_expr_sample.tsv.gz
#       taxon_id: 9606
#   outdir: bgee
#   nodes: False
#   edges: True



coexpression:
  adapter:
    module: biocypher_metta.adapters.coxpresdb_adapter
    cls: CoxpresdbAdapter
    args:
      filepath: ./samples/hsa/coxpressdb
      entrez_to_ensemble_path: ./aux_files/hsa/entrez_to_ensembl.pkl
      taxon_id: 9606
  outdir: coxpresdb
  nodes: False
  edges: True



coexpression_:
  adapter:
    module: biocypher_metta.adapters.coxpresdb_adapter
    cls: CoxpresdbAdapter
    args:
      filepath: ./samples/dmel/coxpresdb
      entrez_to_ensemble_path: ./aux_files/dmel/dmel_entrez_to_ensembl.pkl
      taxon_id: 7227
  outdir: dmel/coxpresdb
  nodes: False
  edges: True

epd_promoter_dmel:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: ./samples/dmel/epd/Dm_EPDnew.bed.gz
      gene_name_to_ensembl_map: ./aux_files/dmel/gene_name_to_id_.pkl
      taxon_id: 7227
  outdir: dmel/epd
  nodes: True
  edges: False

epd_promoter_regulates_gene_dmel:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: ./samples/dmel/epd/Dm_EPDnew.bed.gz
      gene_name_to_ensembl_map: ./aux_files/dmel/gene_name_to_id_.pkl
      type: promoter to gene association
      label: promoter_gene
      taxon_id: 7227
  outdir: dmel/epd
  nodes: False
  edges: True

epd_promoter:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: ./samples/hsa/epd/Hs_EPDnew.bed.gz
      gene_name_to_ensembl_map: ./aux_files/hsa/hgnc_to_ensembl.pkl
      taxon_id: 9606
  outdir: hsa/epd
  nodes: True
  edges: False

epd_promoter_regulates_gene:
  adapter:
    module: biocypher_metta.adapters.epd_adapter
    cls: EPDAdapter
    args:
      filepath: ./samples/hsa/epd/Hs_EPDnew.bed.gz
      gene_name_to_ensembl_map: ./aux_files/hsa/hgnc_to_ensembl.pkl
      type: promoter to gene association
      label: promoter_gene
      taxon_id: 9606
  outdir: hsa/epd
  nodes: False
  edges: True


# uberon:
#   adapter:
#     module: biocypher_metta.adapters.uberon_adapter
#     cls: UberonAdapter
#     args:
#       ontology: 'uberon'
#       type: node
#       dry_run: True
#       add_description: False
#       cache_dir: ./ontology_dataset_cache
#   outdir: uberon
#   nodes: True
#   edges: False

string:
  adapter:
    module: biocypher_metta.adapters.string_ppi_adapter
    cls: StringPPIAdapter
    args:
      filepath: ./samples/dmel/string_7227.protein.links.v12.0.txt.gz
      ensembl_to_uniprot_map: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      taxon_id: 7227
  outdir: dmel/string
  nodes: False
  edges: True


tflink:    
    adapter:
        module: biocypher_metta.adapters.tflink_adapter
        cls: TFLinkAdapter
        args:
          filepath: ./samples/dmel/TFLink_Drosophila_melanogaster_interactions_All_simpleFormat_v1.0.tsv.gz
          entrez_to_ensemble_map: ./aux_files/dmel/dmel_entrez_to_ensembl.pkl
          taxon_id: 7227          
    outdir: dmel/tflink
    nodes: False
    edges: True


uniprotkb_sprot:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      filepath: ./samples/hsa/uniprot_sprot_human_sample.dat.gz
      taxon_id: 9606
  outdir: hsa/uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: ./samples/hsa/uniprot_sprot_human_sample.dat.gz
      type: translates to
      label: translates_to
  outdir: hsa/uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: ./samples/hsa/uniprot_sprot_human_sample.dat.gz
      type: translation of
      label: translation_of
  outdir: hsa/uniprot
  nodes: False
  edges: True


uniprotkb_sprot_dmel:
  adapter:
    module: biocypher_metta.adapters.uniprot_protein_adapter
    cls: UniprotProteinAdapter
    args:
      filepath: ./samples/dmel/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      # filepath: /home/saulo/snet/hyperon/github/das-pk/shared_hsa_dmel2metta/data/full/uniprot/uniprot_sprot_invertebrates.dat.gz
      taxon_id: 7227
  outdir: dmel/uniprot
  nodes: True
  edges: False

uniprotkb_sprot_translates_to_dmel :
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: ./samples/dmel/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      type: translates to
      label: translates_to
      taxon_id: 7227
  outdir: dmel/uniprot
  nodes: False
  edges: True

uniprotkb_sprot_translates_of_dmel:
  adapter:
    module: biocypher_metta.adapters.uniprot_adapter
    cls: UniprotAdapter
    args:
      filepath: ./samples/dmel/uniprot/uniprot_sprot_invertebrates_DMEL.dat.gz
      type: translation of
      label: translation_of
      taxon_id: 7227
  outdir: dmel/uniprot
  nodes: False
  edges: True
