pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactionPMIDS.txt
      taxon_id: 7227
  outdir: reactome
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: genes_pathways
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: parent_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/dmel/dmel_string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 7227
  outdir: reactome
  nodes: False
  edges: True


pathway:
  adapter:
    module: biocypher_metta.adapters.reactome_pathway_adapter
    cls: ReactomePathwayAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathways.txt
      pubmed_map_path: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactionPMIDS.txt
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: True
  edges: False


genes_pathways:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/Ensembl2Reactome_All_Levels.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True


parent_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True

child_pathway_of:
  adapter:
    module: biocypher_metta.adapters.reactome_adapter
    cls: ReactomeAdapter
    args:
      filepath: /mnt/hdd_1/saulo/snet/rejuve.bio/das/shared_rep/data/input/reactome/ReactomePathwaysRelation.txt
      ensembl_uniprot_map_path: ./aux_files/string_ensembl_uniprot_map.pkl
      label: child_pathway_of
      taxon_id: 9606
  outdir: reactome_hsa
  nodes: False
  edges: True

