Title: BioCypher graph schema configuration file (Biolink-adapted for mmu)
# ---
# "Named Things"
# ---

mmusdv subclass of:
  is_a: subclass of
  inherit_properties: true
  represented_as: edge
  input_label: mmusdv_subclass_of
  output_label: is_a
  biolink_predicate: "biolink:subclass_of"
  source: developmental stage
  target: developmental stage
  kgx_properties:
    subject_category: "biolink:LifeStage"
    object_category: "biolink:LifeStage"
    knowledge_level: "knowledge_assertion"
    agent_type: "manual_agent"

##################             NODES   SECTION             ####################



snp:
  represented_as: node
  input_label: snp
  is_a: genomic variant
  mixins: [biolink:Snv]
  biolink_category: "biolink:Snv"
  inherit_properties: true
  kgx_properties:
    category: "biolink:Snv"
  properties:
    ref: 
      type: str
    alt: 
      type: str
    taxon_id:
      type: int
      biolink: taxon
      range: biolink:OrganismTaxon
  description: >-
    A single nucleotide polymorphism (SNP) is a variation in a single nucleotide that occurs at a specific position in the genome
