
emapa:
  adapter:
    module: biocypher_metta.adapters.mmu.emapa_adapter
    cls: EmapaAdapter
    args:
      ontology: "emapa"
      type: node
      label: anatomy
      dry_run: False
      add_description: False
      cache_dir: ./ontology_dataset_cache
  outdir: emapa
  nodes: True
  edges: False

emapa_subclass_of:
  adapter:
    module: biocypher_metta.adapters.mmu.emapa_adapter
    cls: EmapaAdapter
    args:
      ontology: "emapa"
      type: edge
      label: anatomy_subclass_of
      dry_run: False
      cache_dir: ./ontology_dataset_cache
  outdir: emapa
  nodes: False
  edges: True
