input_dir: /mnt/hdd_1/biocypher-kg/input/rno

eva_snp:
  adapter:
    module: biocypher_metta.adapters.eva_adapter
    cls: EVAAdapter
    args:
      filepath: eva/10116_GCA_036323735.1_current_ids.vcf.gz
      taxon_id: 10116
      label: snp
  outdir: rno/eva
  nodes: True
  edges: False

eva_snp_in_gene:
  adapter:
    module: biocypher_metta.adapters.eva_adapter
    cls: EVAAdapter
    args:
      filepath: eva/10116_GCA_036323735.1_current_ids.vcf.gz
      gene_filepath: ensembl/Rattus_norvegicus.GRCr8.115.gtf.gz
      taxon_id: 10116
      label: snp_in_gene
  outdir: rno/eva
  nodes: False
  edges: True
