"""
Validate a KG generated by Neo4jCSVWriter (create_knowledge_graph.py --writer-type
neo4j): checks whether the graph is connected and flags edges whose source/target
type or specific ID never got materialized as a node (i.e. edges that would silently
fail to import into Neo4j, since Neo4jCSVWriter's generated Cypher uses MATCH, not
MERGE, to find edge endpoints).

Usage:
    python scripts/check_kg_connectivity.py --output-dir /tmp/dmel_sample_test
"""

import argparse
import csv
import logging
from collections import Counter, defaultdict
from pathlib import Path

import networkx as nx

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


def load_graph(output_dir):
    output_dir = Path(output_dir)
    graph = nx.Graph()
    node_counts = Counter()
    edge_row_counts = Counter()
    dangling_types = set()  # (source_type, target_type, label) where a type has 0 nodes
    dangling_instances = Counter()  # label -> count of edges whose specific id(s) weren't found

    node_files = sorted(output_dir.rglob("nodes_*.csv"))
    for nf in node_files:
        label = nf.stem[len("nodes_"):]
        with open(nf, newline="") as f:
            reader = csv.DictReader(f, delimiter="|")
            for row in reader:
                node_key = (label, row["id"])
                graph.add_node(node_key, label=label)
                node_counts[label] += 1
    logger.info("Loaded %d node files, %d total nodes", len(node_files), sum(node_counts.values()))

    known_types = set(node_counts.keys())
    edge_files = sorted(output_dir.rglob("edges_*.csv"))
    for ef in edge_files:
        with open(ef, newline="") as f:
            reader = csv.DictReader(f, delimiter="|")
            for row in reader:
                src_type, tgt_type, label = row["source_type"], row["target_type"], row["label"]
                edge_row_counts[label] += 1
                if src_type not in known_types or tgt_type not in known_types:
                    dangling_types.add((src_type, tgt_type, label))
                    continue
                src_key, tgt_key = (src_type, row["source_id"]), (tgt_type, row["target_id"])
                if src_key in graph and tgt_key in graph:
                    graph.add_edge(src_key, tgt_key, label=label)
                else:
                    dangling_instances[label] += 1
    logger.info("Loaded %d edge files, %d total edge rows", len(edge_files), sum(edge_row_counts.values()))

    return graph, node_counts, edge_row_counts, dangling_types, dangling_instances


def report(output_dir):
    graph, node_counts, edge_row_counts, dangling_types, dangling_instances = load_graph(output_dir)

    print("\n" + "=" * 60)
    print("  KG CONNECTIVITY REPORT")
    print("=" * 60)
    print(f"  Nodes loaded : {sum(node_counts.values()):,} across {len(node_counts)} types")
    print(f"  Edge rows    : {sum(edge_row_counts.values()):,} across {len(edge_row_counts)} labels")
    resolved_edges = graph.number_of_edges()
    total_edge_rows = sum(edge_row_counts.values())
    print(f"  Edges resolved into graph: {resolved_edges:,} / {total_edge_rows:,}")

    if graph.number_of_nodes() == 0:
        print("  No nodes loaded — nothing to check.")
        return

    components = sorted(nx.connected_components(graph), key=len, reverse=True)
    print(f"\n  Connected components: {len(components)}")
    for i, comp in enumerate(components[:10]):
        print(f"    #{i + 1}: {len(comp)} nodes")
    if len(components) > 10:
        print(f"    ... and {len(components) - 10} more")

    if dangling_types:
        print(f"\n  Edge (source_type, target_type, label) combos with a MISSING node type "
              f"({len(dangling_types)}):")
        for src_type, tgt_type, label in sorted(dangling_types):
            print(f"    - {label}: {src_type} -> {tgt_type}")
    else:
        print("\n  No edge type references a node type with zero nodes.")

    if dangling_instances:
        print(f"\n  Edge labels with unresolved specific IDs (type exists, this ID doesn't):")
        for label, count in dangling_instances.most_common():
            print(f"    - {label}: {count} edges")
    else:
        print("  No edges with unresolved specific source/target IDs.")

    print("=" * 60 + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, help="KG output dir passed to create_knowledge_graph.py")
    args = parser.parse_args()
    report(args.output_dir)


if __name__ == "__main__":
    main()
